Repository Trailiva/trailiva-web, pull requests merged in 2022-09, with the labels that each got.

#22 implement navbar
  src/components/Buttons/CustomButton.js
  src/components/Navbar.js
  src/pages/auth/register/register.css
Labels: documentation

#24 Trail 141 redesign authentication pages
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/components/InputFields/IsInputComponent.module.css
  src/components/Navbar.js
  src/pages/auth/login/Login.js
  src/pages/auth/register/Register.js
  src/pages/auth/register/register.css
Labels: enhancement

#27 Trail 84 redesign verify account page
  .eslintrc.json
  package.json
  src/App.js
  src/components/InputFields/IsInputComponent.js
  src/components/IsAlertToast.js
  src/components/Navbar.js
  src/components/TaskCreator.js
  src/pages/auth/login/Login.js
  src/pages/auth/register/Register.js
  src/pages/auth/register/register.css
  src/pages/auth/verificationPage/ToVerify.js
  src/pages/auth/verificationPage/verification.css
  src/pages/tasks/ViewTask.js
  yarn.lock
Labels: documentation

#28 Trail 190 implement create new password page
  src/App.js
  src/components/InputFields/IsInputComponent.js
  src/constants/index.js
  src/pages/auth/forgetPassword/CreateNewPassword.js
  src/pages/auth/login/Login.js
  src/pages/auth/verificationPage/verification.css
  src/services/authService.js
  src/store/auth-actions.js
  src/store/auth-slice.js
Labels: documentation, enhancement

#29 Trail 190 implement create new password page
  src/constants/index.js
  src/store/auth-actions.js
Labels: documentation

#30 TRAIL-191:redesign-forgot-password-page
  package-lock.json
  src/pages/auth/forgetPassword/ForgetPassword.js
  src/services/authService.js
  src/store/auth-actions.js
  src/utils/helper.js
Labels: enhancement

#31 TRAIL-192: implement create project page
  .env
  src/App.js
  src/components/Navbar.js
  src/pages/auth/ResetPassword/UpdatePassword.js
  src/pages/auth/forgetPassword/ForgetPassword.js
  src/pages/auth/forgetPassword/ResetPassword.js
  src/pages/auth/login/Login.js
  src/pages/auth/register/Register.js
  src/pages/auth/register/register.css
  src/pages/dashboard/Dashboard.js
  src/pages/project/CreateProject.js
  src/pages/tasks/TaskContainer.js
  src/pages/workspace/personal/CreateWorkspace.js
  src/pages/workspace/personal/personal.css
  src/services/projectService.js
  src/services/taskService.js
  src/services/workspaceService.js
  src/store/auth-action.js
  src/store/index.js
  src/store/project-action.js
  src/store/project-slice.js
  src/store/workspace-action.js
Labels: enhancement

#32 Trail 85 redesign workspace creation page
  src/App.js
  src/components/Navbar.js
  src/pages/auth/register/register.css
  src/pages/workspace/personal/CreateWorkspace.js
  src/pages/workspace/personal/personal.css
  src/utils/formValidation.js
Labels: enhancement
